import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Enhanced sidebar with better organization and features from 3.8+

  // docSidebar: [{type: 'autogenerated', dirName: '.'}],

  docSidebar: [
    'about',
    'getting-started',
    {
      type: 'category',
      label: '🔧 Core',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'core'},
      ],
    },
    {
      type: 'category',
      label: '👷 Operators',
      link: {
        type: 'doc',
        id: 'operator/index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'operator'},
      ],
    },
    {
      type: 'category',
      label: '🔍 Plugins',
      link: {
        type: 'doc',
        id: 'plugins/index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'plugins'},
      ],
    },
    {
      type: 'category',
      label: '📦 Troubleshooting',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'troubleshooting'},
      ],
    },
    {
      type: 'category',
      label: '📊 Comparison',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'comparison'},
      ],
    },
    {
      type: 'category',
      label: '🌐 Blog',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'link', href: 'https://samuelberthe.substack.com/p/go-beyond-goroutines-introducing', label: 'Go beyond Goroutines: introducing the Reactive Programming paradigm' },
      ],
    },
    'testing',
    'hacking',
    'contributing',
    'glossary',
  ],
};

export default sidebars;
